<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;

use Illuminate\Support\Facades\Schema;

class CreateSectionStylesTable extends Migration
{
    public function up()
    {
        Schema::create('section_styles', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('section_id');
            $table->string('section_style_name');
            $table->string('file_path');
            $table->string('file_slug');
            $table->boolean('status')->default(true); // or use `$table->tinyInteger('status')->default(1);` for MySQL `TINYINT`

            // Foreign key constraint
            $table->foreign('section_id')->references('id')->on('sections')->onDelete('cascade');

            $table->timestamps();
        });
        DB::table('section_styles')->insert([
            [
                "id" => "1",
                "section_id" => "1",
                "section_style_name" => "Style 1",
                "file_path" => "HeroStyle1.blade.php",
                "file_slug" => "HeroStyle1",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "2",
                "section_id" => "1",
                "section_style_name" => "Style 2",
                "file_path" => "HeroStyle2.blade.php",
                "file_slug" => "HeroStyle2",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "3",
                "section_id" => "1",
                "section_style_name" => "Style 3",
                "file_path" => "HeroStyle3.blade.php",
                "file_slug" => "HeroStyle3",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "4",
                "section_id" => "1",
                "section_style_name" => "Style 4",
                "file_path" => "HeroStyle4.blade.php",
                "file_slug" => "HeroStyle4",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "5",
                "section_id" => "1",
                "section_style_name" => "Style 5",
                "file_path" => "HeroStyle5.blade.php",
                "file_slug" => "HeroStyle5",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "6",
                "section_id" => "1",
                "section_style_name" => "Style 6",
                "file_path" => "HeroStyle6.blade.php",
                "file_slug" => "HeroStyle6",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "7",
                "section_id" => "1",
                "section_style_name" => "Style 7",
                "file_path" => "HeroStyle7.blade.php",
                "file_slug" => "HeroStyle7",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "8",
                "section_id" => "1",
                "section_style_name" => "Style 8",
                "file_path" => "HeroStyle8.blade.php",
                "file_slug" => "HeroStyle8",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "9",
                "section_id" => "2",
                "section_style_name" => "Style 1",
                "file_path" => "TestimonialStyle1.blade.php",
                "file_slug" => "TestimonialStyle1",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "10",
                "section_id" => "2",
                "section_style_name" => "Style 2",
                "file_path" => "TestimonialStyle2.blade.php",
                "file_slug" => "TestimonialStyle2",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "11",
                "section_id" => "2",
                "section_style_name" => "Style 3",
                "file_path" => "TestimonialStyle3.blade.php",
                "file_slug" => "TestimonialStyle3",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "12",
                "section_id" => "3",
                "section_style_name" => "Style 1",
                "file_path" => "CallToActionStyle1.blade.php",
                "file_slug" => "CallToActionStyle1",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "13",
                "section_id" => "3",
                "section_style_name" => "Style 2",
                "file_path" => "CallToActionStyle2.blade.php",
                "file_slug" => "CallToActionStyle2",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "14",
                "section_id" => "3",
                "section_style_name" => "Style 3",
                "file_path" => "CallToActionStyle3.blade.php",
                "file_slug" => "CallToActionStyle3",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "15",
                "section_id" => "3",
                "section_style_name" => "Style 4",
                "file_path" => "CallToActionStyle4.blade.php",
                "file_slug" => "CallToActionStyle4",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "16",
                "section_id" => "3",
                "section_style_name" => "Style 5",
                "file_path" => "CallToActionStyle5.blade.php",
                "file_slug" => "CallToActionStyle5",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "17",
                "section_id" => "4",
                "section_style_name" => "Style 1",
                "file_path" => "TabStyle1.blade.php",
                "file_slug" => "TabStyle1",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "18",
                "section_id" => "4",
                "section_style_name" => "Style 2",
                "file_path" => "TabStyle2.blade.php",
                "file_slug" => "TabStyle2",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "19",
                "section_id" => "5",
                "section_style_name" => "Style 1",
                "file_path" => "ServiceStyle1.blade.php",
                "file_slug" => "ServiceStyle1",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "20",
                "section_id" => "5",
                "section_style_name" => "Style 2",
                "file_path" => "ServiceStyle2.blade.php",
                "file_slug" => "ServiceStyle2",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "21",
                "section_id" => "5",
                "section_style_name" => "Style 3",
                "file_path" => "ServiceStyle3.blade.php",
                "file_slug" => "ServiceStyle3",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "22",
                "section_id" => "6",
                "section_style_name" => "Style 1",
                "file_path" => "WorkProcessStyle1.blade.php",
                "file_slug" => "WorkProcessStyle1",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "23",
                "section_id" => "6",
                "section_style_name" => "Style 2",
                "file_path" => "WorkProcessStyle2.blade.php",
                "file_slug" => "WorkProcessStyle2",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "24",
                "section_id" => "6",
                "section_style_name" => "Style 3",
                "file_path" => "WorkProcessStyle3.blade.php",
                "file_slug" => "WorkProcessStyle3",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "25",
                "section_id" => "6",
                "section_style_name" => "Style 4",
                "file_path" => "WorkProcessStyle4.blade.php",
                "file_slug" => "WorkProcessStyle4",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "26",
                "section_id" => "7",
                "section_style_name" => "Style 1",
                "file_path" => "PricingStyle1.blade.php",
                "file_slug" => "PricingStyle1",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "27",
                "section_id" => "7",
                "section_style_name" => "Style 2",
                "file_path" => "PricingStyle2.blade.php",
                "file_slug" => "PricingStyle2",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "28",
                "section_id" => "7",
                "section_style_name" => "Style 3",
                "file_path" => "PricingStyle3.blade.php",
                "file_slug" => "PricingStyle3",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "29",
                "section_id" => "8",
                "section_style_name" => "Style 1",
                "file_path" => "FaqStyle1.blade.php",
                "file_slug" => "FaqStyle1",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "30",
                "section_id" => "8",
                "section_style_name" => "Style 2",
                "file_path" => "FaqStyle2.blade.php",
                "file_slug" => "FaqStyle2",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "31",
                "section_id" => "9",
                "section_style_name" => "Style 1",
                "file_path" => "FeatureStyle1.blade.php",
                "file_slug" => "FeatureStyle1",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "32",
                "section_id" => "9",
                "section_style_name" => "Style 2",
                "file_path" => "FeatureStyle2.blade.php",
                "file_slug" => "FeatureStyle2",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "33",
                "section_id" => "9",
                "section_style_name" => "Style 3",
                "file_path" => "FeatureStyle3.blade.php",
                "file_slug" => "FeatureStyle3",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "34",
                "section_id" => "9",
                "section_style_name" => "Style 4",
                "file_path" => "FeatureStyle4.blade.php",
                "file_slug" => "FeatureStyle4",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "35",
                "section_id" => "9",
                "section_style_name" => "Style 5",
                "file_path" => "FeatureStyle5.blade.php",
                "file_slug" => "FeatureStyle5",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "36",
                "section_id" => "9",
                "section_style_name" => "Style 6",
                "file_path" => "FeatureStyle6.blade.php",
                "file_slug" => "FeatureStyle6",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "37",
                "section_id" => "9",
                "section_style_name" => "Style 7",
                "file_path" => "FeatureStyle7.blade.php",
                "file_slug" => "FeatureStyle7",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "38",
                "section_id" => "9",
                "section_style_name" => "Style 8",
                "file_path" => "FeatureStyle8.blade.php",
                "file_slug" => "FeatureStyle8",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "39",
                "section_id" => "10",
                "section_style_name" => "Style 1",
                "file_path" => "IntegrationStyle1.blade.php",
                "file_slug" => "IntegrationStyle1",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "40",
                "section_id" => "10",
                "section_style_name" => "Style 2",
                "file_path" => "IntegrationStyle2.blade.php",
                "file_slug" => "IntegrationStyle2",
                "status" => "1",
                "created_at" => "2024-08-22 10:47:45",
                "updated_at" => "2024-08-22 10:47:45",
            ],
            [
                "id" => "41",
                "section_id" => "14",
                "section_style_name" => "Style 1",
                "file_path" => "HelpCenterStyle1.blade.php",
                "file_slug" => "HelpCenterStyle1",
                "status" => "1",
                "created_at" => "2024-08-30 12:00:07",
                "updated_at" => "2024-08-30 12:00:07",
            ],
            [
                "id" => "42",
                "section_id" => "12",
                "section_style_name" => "Style 1",
                "file_path" => "BlogStyle1.blade.php",
                "file_slug" => "BlogStyle1",
                "status" => "1",
                "created_at" => "2024-09-09 08:59:31",
                "updated_at" => "2024-09-09 08:59:31",
            ],
            [
                "id" => "43",
                "section_id" => "12",
                "section_style_name" => "Style 2",
                "file_path" => "BlogStyle2.blade.php",
                "file_slug" => "BlogStyle2",
                "status" => "1",
                "created_at" => "2024-09-09 08:59:54",
                "updated_at" => "2024-09-09 08:59:54",
            ],
            [
                "id" => "44",
                "section_id" => "12",
                "section_style_name" => "Style 3",
                "file_path" => "BlogStyle3.blade.php",
                "file_slug" => "BlogStyle3",
                "status" => "1",
                "created_at" => "2024-09-09 09:02:40",
                "updated_at" => "2024-09-09 09:02:40",
            ],
            [
                "id" => "45",
                "section_id" => "11",
                "section_style_name" => "Style 1",
                "file_path" => "OurTeamStyle1.blade.php",
                "file_slug" => "OurTeamStyle1",
                "status" => "1",
                "created_at" => "2024-09-09 11:11:09",
                "updated_at" => "2024-09-09 11:11:09",
            ],
            [
                "id" => "46",
                "section_id" => "11",
                "section_style_name" => "Style 2",
                "file_path" => "OurTeamStyle2.blade.php",
                "file_slug" => "OurTeamStyle2",
                "status" => "1",
                "created_at" => "2024-09-09 11:11:34",
                "updated_at" => "2024-09-09 11:11:34",
            ],
            [
                "id" => "47",
                "section_id" => "13",
                "section_style_name" => "Style 1",
                "file_path" => "ContactStyle1.blade.php",
                "file_slug" => "ContactStyle1",
                "status" => "1",
                "created_at" => "2024-09-09 11:20:01",
                "updated_at" => "2024-09-09 11:20:01",
            ],
            [
                "id" => "48",
                "section_id" => "5",
                "section_style_name" => "Style 4",
                "file_path" => "ServiceStyle4.blade.php",
                "file_slug" => "ServiceStyle4",
                "status" => "1",
                "created_at" => "2024-11-28 09:51:38",
                "updated_at" => "2024-11-28 09:51:38",
            ],
            [
                "id" => "49",
                "section_id" => "5",
                "section_style_name" => "Style 5",
                "file_path" => "ServiceStyle5.blade.php",
                "file_slug" => "ServiceStyle5",
                "status" => "1",
                "created_at" => "2024-11-28 10:50:50",
                "updated_at" => "2024-11-28 10:50:50",
            ],
            [
                "id" => "50",
                "section_id" => "10",
                "section_style_name" => "Style 3",
                "file_path" => "IntegrationStyle3.blade.php",
                "file_slug" => "IntegrationStyle3",
                "status" => "1",
                "created_at" => "2024-11-29 04:25:25",
                "updated_at" => "2024-11-29 04:25:25",
            ],
            [
                "id" => "51",
                "section_id" => "10",
                "section_style_name" => "Style 4",
                "file_path" => "IntegrationStyle4.blade.php",
                "file_slug" => "IntegrationStyle4",
                "status" => "1",
                "created_at" => "2024-11-29 05:39:54",
                "updated_at" => "2024-11-29 05:39:54",
            ],
            [
                "id" => "52",
                "section_id" => "10",
                "section_style_name" => "Style 5",
                "file_path" => "IntegrationStyle5.blade.php",
                "file_slug" => "IntegrationStyle5",
                "status" => "1",
                "created_at" => "2024-11-29 05:49:18",
                "updated_at" => "2024-11-29 05:49:18",
            ],
        ]);
    }

    public function down()
    {
        Schema::dropIfExists('section_styles');
    }
}
