@extends('applicant.body.app')
<style>
    .modal-dialog {
      max-width: 80%; /* Increased width from 60% to 80% */
    }

    .terms-content {
      max-height: 60vh;
      overflow-y: auto;
      padding: 20px;
      background-color: #f8f9fa;
      border: 1px solid #ddd;
    }
  </style>
@section('content')
<div class="modal fade" id="termsModal" tabindex="-1" aria-labelledby="termsModalLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="termsModalLabel">Terms and Conditions</h5>
      </div>
      <div class="modal-body">             
              @if ($errors->any())
              <div class="alert alert-danger alert-messages">
                  <ul>
                      @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                      @endforeach
                  </ul>
              </div>
              @endif
        <div class="terms-content" id="termsContent">
          <!-- Insert your long Terms and Conditions content here -->
           
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...</p>
          <p>(Add long content here to make the div scrollable) Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, mi vel sodales euismod...

</p>
</div>
<form action="{{ route('applicant.acceptTerms.post')}}" method="post">
  @csrf
        <div class="mt-3">
          <input type="checkbox" id="acceptTerms" name="accept_terms_condition" value="1" required disabled> 
          I have read and agree to the Terms and Conditions
        </div>
      </div>
      <div class="modal-footer">
        <button type="submit" id="submitBtn" class="btn btn-primary" disabled>Submit</button>
      </div>
      </form>
    </div>
  </div>
</div>
<script>
$(document).ready(function() {
  // Automatically open modal when page loads
  $('#termsModal').modal('show');

  var $termsContent = $('#termsContent');
  var $acceptTerms = $('#acceptTerms');
  var $submitBtn = $('#submitBtn');

  // Enable the checkbox when scrolled to the bottom
  $termsContent.on('scroll', function() {
    if ($termsContent[0].scrollHeight - $termsContent.scrollTop() <= $termsContent.outerHeight()) {
      $acceptTerms.prop('disabled', false); // Enable checkbox when bottom is reached
    }
  });

  // Enable the submit button only when the checkbox is checked
  $acceptTerms.on('change', function() {
    if ($acceptTerms.is(':checked')) {
      $submitBtn.prop('disabled', false); // Enable the button when checkbox is checked
    } else {
      $submitBtn.prop('disabled', true);
    }
  });
});
</script>
@endsection